version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building project...
      - npm test || echo "No tests found"

artifacts:
  files:
    - app.js
    - appspec.yml
    - scripts/**
